### G.E

- 행렬 A 는 궁극적으로 Upper Triangle Matrix 와 Low Triangle Matrix 그리고 Permutation Matrix의 곱으로 분해 될 수 있다.

`A = P.T * L * U`

- LU분해의 의의
    - 연산이 편해지고, 역행렬을 구하기 쉬우며, determinant도 구하기 쉽다. 
    - 즉, 전체적인 연산속도 향상이 가능하다.
                
##### 행렬 A 를 하나의 선형시스템으로 생각하면 input 과 ouput을 보고 시스템 A 안에서, 어떠한 계수로 연산이 일어나는지를 LU분해를 통해 찾아 낼 수 있다.


In [40]:
import numpy as np
import numpy.linalg as lin

In [12]:
# 연립방정식 Ax = b
# 2u + v + w = 5
# 4u - 6v    = -2
# -2u + 7v + 2w = 9

A = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
b = np.array([5, -2, 9])

A, b

(array([[ 2,  1,  1],
        [ 4, -6,  0],
        [-2,  7,  2]]), array([ 5, -2,  9]))

In [22]:
E21 = np.array([[1, 0, 0], [-2, 1, 0], [0, 0, 1]])
E21

array([[ 1,  0,  0],
       [-2,  1,  0],
       [ 0,  0,  1]])

In [23]:
E31 = np.array([[1, 0, 0], [0, 1, 0], [1, 0, 1]])
E31

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 1]])

In [24]:
E32 = np.array([[1, 0, 0], [0, 1, 0], [0, 1, 1]])
E32

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 1]])

In [31]:
E21A = E21.dot(A)
E21A

array([[ 2,  1,  1],
       [ 0, -8, -2],
       [-2,  7,  2]])

In [35]:
E31E21A = E31.dot(E21A)
E31E21A

array([[ 2,  1,  1],
       [ 0, -8, -2],
       [ 0,  8,  3]])

In [37]:
E32E31E21A = E32.dot(E31E21A)
E32E31E21A

array([[ 2,  1,  1],
       [ 0, -8, -2],
       [ 0,  0,  1]])

In [39]:
U = E32E31E21A

#### Elementary matrix in G.E
- E21 과 inverse E21에 차이는 부호 뿐이다.(역행렬 연산의 간단함)
- Elementary matrix의 역행렬은 해당되는 행렬값 부호만 바꾸어주면 된다. ex) E21 이면 2행 1렬의 값의 부호만 변경하면 역행렬이 됨.

### A = L * U

In [44]:
# A = E21^-1 * E31^-1 * E32^-1 * U (^-1 is inverse matrix)

invE32 = lin.inv(E32)
invE31 = lin.inv(E31)
invE21 = lin.inv(E21)

print(invE32)
print(invE31)
print(invE21)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-1.  0.  1.]]
[[ 1. -0. -0.]
 [ 2.  1.  0.]
 [ 0.  0.  1.]]


In [46]:
invE32U= invE32.dot(U)
invE32U

array([[ 2.,  1.,  1.],
       [ 0., -8., -2.],
       [ 0.,  8.,  3.]])

In [47]:
invE31invE32U= invE31.dot(invE32U)
invE31invE32U

array([[ 2.,  1.,  1.],
       [ 0., -8., -2.],
       [-2.,  7.,  2.]])

In [49]:
invE21invE31invE32U = invE21.dot(invE31invE32U)
invE21invE31invE32U

array([[ 2.,  1.,  1.],
       [ 4., -6.,  0.],
       [-2.,  7.,  2.]])

In [50]:
invE21invE31invE32U == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [52]:
inv31invE32 = invE31.dot(invE32)
inv31invE32

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-1., -1.,  1.]])

In [53]:
invE21inv31invE32 = invE21.dot(inv31invE32)
invE21inv31invE32

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [-1., -1.,  1.]])

In [54]:
L = invE21inv31invE32

In [55]:
A

array([[ 2,  1,  1],
       [ 4, -6,  0],
       [-2,  7,  2]])

In [56]:
L.dot(U)

array([[ 2.,  1.,  1.],
       [ 4., -6.,  0.],
       [-2.,  7.,  2.]])

In [58]:
A == L.dot(U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

### Pivoting
- Row exchange => permutation Matrix
- Permutaion matrix has the same rows with identity matrix
- There is a single "1" in every row and column

#### A = L*U, 
#### P*A = L*U -> A = invP*L*U

- Permutaion matrix의 역행렬은 p-matrix를 transpose한 것과 같다.
- Permutaion matrix는 기본적인 행렬의 연산의 법칙을 따른다. 교환법칙 X

In [64]:
P21 = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
P21

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [65]:
invP21 = lin.inv(P21)
invP21

array([[ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [66]:
P21.T

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [67]:
P31 = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
P31

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [69]:
P32 = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
P32

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])