## 1.6  Inverse & Transpose

#### Inverse (역행렬)

- A * invA = invA * A = I (교환법칙이 성립해야 한다)
- not all A has its inverse
- det(A) != 0 이어야 역행렬이 존재한다.

#### (1) The inverse (invA) exists iff(if and only if) elimination(G.E) produces n(diagonal elements) pivots

- G.E(A) = U >>> invL * A = U >>>  A = L * U
- invL = E32E31E21
- [det(A) != 0] == product of all diagonal elements

#### (2) The inverse is Unique!

- prof) invA = B, invA = C
- (B*A)*C = B*(A*C)
- C = B

#### (3) If invA exists, x is Unique!

- Ax = b
- invA*A*x = invA*b
- x와 b는 A라는 함수 안에서 일대일 대응관계를 유지한다.

#### (4) Assume that there is a non-zero vector x such that

- Ax = 0 (b=0)
- x = 0 (trivial solution)
- invA*0 = x = 0
- then, invA does not exist, 위 조건을 만족하려면 역행렬이 존재하면 안된다.

#### (5) 2 * 2 행렬 determinant 식

In [2]:
import numpy as np

a = 1
b = 2
c = 3
d = 4

A = np.array([[a, b],[c, d]])
A

array([[1, 2],
       [3, 4]])

In [5]:
detA = (a*d) - (b*c)
detA

-2

#### (6) Diagonal Matrix

- 대각 성분 di가 모두 0이 아니어야 한다.
- 대각 행렬의 역행렬은 대각성분을 모두 역수 취한 행렬과 같다.

#### (7) The inverse comes in the reverse order

- inv(A*B*C) = invC*invB*invC

### Gauss - Jordan Method

- Ax = b

- AB = A[b1, b2, ... , bn] = [Ab1, Ab2, ... , Abn]
- A * invA = I, invA = [x1, x2, ... , xn]
- [Ax1, Ax2, ... , Axn] = I matrix

```즉, Ax1 = [1, 0, 0, ... ,0]
    Ax2 = [0, 1, 0, ... ,0]
    Axn = [0, 0, 0, ... ,1]
    가우스 소거법을 사용하면 역행렬을 구하는 과정
    ```

- G.E(A) = U
- E32E31E21A = U, E32E31E21 = invL
- invL * A = U
```
 A * invA = I
 U * invA = invL * I
 invU * U * invA = invU * invL * I
 invA = invU * invL * I
```

#### Transpose

In [6]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
A2 = np.array([[1, 2, 3],[4, 5, 6]])
A2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
A2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

- (A + B).T = A.T + B.T
- (A*B).T = B.T * A.T
- invA.T = inv(A.T)

#### Symmetric Matrix

- square Matrix
- A.T = A
- if A is symmetric and invertible then, invA is too.
- (invA).T = invA

```
A = L*U = L*D(diagonal Matrix)*U
invA = A
L * D * U = U.T * D * L.T
```

#### Correlation Matrix(R)

- R = A.T * A
- R.T = R
- 벡터들이 어떤 상관관계인지 알게 해주는 연산